### ISSUE TITLE
new source

### ISSUE THREAD

**Issue by felipe-negri** [kingbri1/Tsuchi#17]
add https://mangalivre.net/ support please

**Comment by kingbri1** [comment]
Unfortunately, I cannot access this source. I have also asked a few friends to try it, but we keep getting an error 1020 from cloudflare when accessing the site.

If you have any alternatives you use, please link them below. Image is attached

![image](https://user-images.githubusercontent.com/8082010/128559384-9ae93edb-37db-4fd9-b6ae-2f2fa00645a5.png)

**Comment by kingbri1** [comment]
Closing this issue as it is stale. Please open a new issue if an alternative source has been found or if this website lifts its cloudflare restrictions.
